# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'notification-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for notification-test
  pod 'SimulatorRemoteNotifications', '~> 0.0.3'

  target 'notification-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'notification-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
